//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identityyy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listbook
    {
        public int id { get; set; }
        public string namebook { get; set; }
        public string decbook { get; set; }
        public Nullable<double> price { get; set; }
        public string cover { get; set; }
    }
}
